import os
from datetime import datetime, timedelta
from github import Github


def get_weekly_stats():
    # GitHub Token aus den Actions Secrets (oder lokal .env)
    token = os.getenv('GITHUB_TOKEN')
    repo_name = os.getenv('GITHUB_REPOSITORY')  # Format: 'Nutzer/Repo'

    repo = Github(token).get_repo(repo_name)

    last7days = datetime.now() - timedelta(days=7)

    # time period
    issues = repo.get_issues(state='all', since=last7days)

    opened_count = 0
    closed_count = 0
    closed_titles = []

    for issue in issues:
        if issue.pull_request:
            continue

        if issue.created_at > last7days:
            opened_count += 1

        if issue.state == 'closed' and issue.closed_at > last7days:
            closed_count += 1
            closed_titles.append(f"- {issue.title} (#{issue.number})")

    delta = closed_count - opened_count
    status_emoji = "🚀" if delta >= 0 else "⚠️"


    report_md = f"""
## {status_emoji} Weekly progress report
*Time period: {last7days.strftime('%d.%m.')} - {datetime.now().strftime('%d.%m.%Y')}*

### 📊 statistics
- **New opended Issues:** {opened_count}
- **closed Issues:** {closed_count}
- **progress:** {delta:+d} 

### ✅ Ready Tasks
{chr(10).join(closed_titles) if closed_titles else "Keine Issues diese Woche geschlossen."}

---
*Automatically generated by GitHub Project Summary*
    """

    return report_md


def post_as_issue(content):
    token = os.getenv('GITHUB_TOKEN')
    repo_name = os.getenv('GITHUB_REPOSITORY')
    g = Github(token)
    repo = g.get_repo(repo_name)

    # Erstellt ein neues Issue mit dem Bericht
    repo.create_issue(
        title=f"Progress Report: {datetime.now().strftime('%Y-W%V')}",
        body=content
    )


if __name__ == "__main__":
    report = get_weekly_stats()
    print(report)
    post_as_issue(report)